# Site settings
title: Tan's blog
email: 
description: "Hmm..."
baseurl: ""
url: "http://mserkantan.github.io"
github_username:  "mserkantan"
twitter_username: "mserkantan"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
